name: Full Frontend Build, Format, and Test

on:
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main

defaults:
  run:
    working-directory: frontend

env:
  node-version: 14.x

jobs:
  build:
    name: Full build validation
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ env.node-version }}

      - name: Validate Frontend
        run: |
          npm ci
          npm run validate

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          working-directory: frontend

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
        with:
          working-directory: frontend

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          working-directory: frontend
